# COMS W1002 Computing in Context: Computational Finance  
## Professor Karl Sigman
## Option Pricing Using Monte Carlo Simulation

__Problem 1:__ For the values of $p=0.5$ and $p=0.75$ obtain an estimate of $p$ by using Monte Carlo Simulation with $n=100, n=1000, n=10,000$ You will generate $n$ _iid_ Bernoulli $(p)$ random variables $B_1, ..., B_n$ and use as the estimate $$ \hat{p}= \frac{1}{n}\sum_{i=1}^{n}B_i $$ 
This is to show you (convince you) how accurate the Monte Carlo method can be, and how the Strong Law of Large Numbers (SLLN) works in practice.

In [13]:
import random
import numpy as np
import math

In [128]:
# p = .5

# a single bernoulli rv with probability .5 

def bern(p):
    # generate a random decimal between 0 and 1
    U = random.random()
    # condition for successful trial
    if U<=p:
        #success = 1
        return 1
    return 0

bern(.5)


0

In [117]:
# p = .75

# a single bernoulli rv with probability .75 

bern(.75)

1

In [129]:
# n = 100, p = .5
# counts number of successful bernoulli trials divided by total trials n

# set probability to .5
p = .5

# a function that returns the ratio of successful trials N to total trials n with p = .5
def total_success(n):
    N = 0
    for i in range(n):
        N = N+bern(p)
    print('Of ', n, ' trials with probability', p,'the number of successful trials, where (U <= p) was ', N)
    return N, N/n
   

total_success(100)

Of  100  trials with probability 0.5 the number of successful trials, where (U <= p) was  48


(48, 0.48)

In [130]:
# n = 1000, p = .5

# becoming increasingly accurate as n -> infinity

total_success(1000)

Of  1000  trials with probability 0.5 the number of successful trials, where (U <= p) was  510


(510, 0.51)

In [131]:
# n =1000, p = .5

total_success(10000)

Of  10000  trials with probability 0.5 the number of successful trials, where (U <= p) was  4918


(4918, 0.4918)

In [19]:
# n = 100, p = .75

# adjusting the probability to .75 because why not 
p = .75

total_success(100)

Of  100  trials with probability 0.75 the number of successful trials, where (U <= p) was  73


(73, 0.73)

In [20]:
# n = 1000, p = .75

total_success(1000)

Of  1000  trials with probability 0.75 the number of successful trials, where (U <= p) was  739


(739, 0.739)

In [21]:
# n = 10000, p = .75

total_success(10000)

# Very cool and mathematical
# as n -> infinity, the output of the total_success() function -> .75
# the more trials performed, the more accurate the output becomes. Neat.  

Of  10000  trials with probability 0.75 the number of successful trials, where (U <= p) was  7508


(7508, 0.7508)

In [133]:
outcomes = []

def binomial(n,p_star):
    total = 0
    for k in range(n):
        outcomes.append(bern(p))
        total += bern(p)
    return total, total/n, outcomes[0:20]

binomial(10,.4)


(4915, 0.4915, [1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1])

## Assuming that 0 < d < 1 +r < u, we see that 0 < p* < 1 can be viewed as a probability

# BLM path with p = .5

# Variables and formulas 

In [24]:
T = 10
r = 0.05
u = 1.15
d = 1.01
S0 = 50
K = 70
p = .5
k = k_total(T,d)

In [134]:
# same as bern(p) function

def Yrv(p_star,u,d):
    U = random.random()
    if U <= p_star:
        return u
    return d


# sum of all k = 0 results out of T bernoulli trials 
def k_total(T,d):
    k = 0
    for i in range(T):
        if Yrv(p_star,u,d) == d:
            k += 1
    return k

0.28571428571428614

In [148]:
Yrv(p_star,u,d)

1.01

In [154]:
k_total(T,d)

7

In [155]:
# ratio of k failures where k = d 
bino_dist_k = k/T

#expected payoff C at T=1 for both options u and d
C1_u = (u*S0 - K)
C1_d = (d*S0 - K)

if C1_u > 0:
    C1_u
else: 
    C1_u = 0
    print(C1_u)
    
if C1_d > 0:
    C1_d
else: 
    C1_d = 0
    print(C1_d)
    
p_star = (1 + r - d) / (u - d)    

# share price S at time t
St = u**k*d**(T-k)    

# number of ways you can have k successes/failures from total T
T_choose_k = math.comb(T,k)    

# the risk-free return rate of putting your money in the bank with r =0.05
disc_rate = 1 / (1+r)**T    

# payoff C at time t with a strike price of K
Ct = (St - K)    

# expected payout C after 1 day
Exp_C1 = p*C1_u + (1-p)*C1_d


E_star_C1 = p_star*C1_u + (1-p_star)*C1_d

# option price 
C_zero = 1 / (1+r) * E_star_C1


Exp_val_Y_rv = p*u + (1-p)*d

Exp_val_S1 = S0*(p*u + (1-p)*d)


E_star_C1 = p_star*C1_u + (1-p_star)*C1_d

C0_test = E_star_C1*disc_rate


print(T_choose_k)
print(T)
print(r)
print(u)
print(d)
print(S0)
print(p)
print(k)
print(bino_dist_k)
print(Exp_C1)
print(E_star_C1)
print(C_zero)
print(Exp_val_Y_rv)
print(Exp_val_S1)
print(C0_test)
print(p_star)
print(E_star_C1)
print(Ct)
print(St)

0
0
252
10
0.05
1.15
1.01
50
0.5
5
0.5
0.0
0.0
0.0
1.08
54.0
0.0
0.28571428571428614
0.0
-67.88604338159664
2.11395661840337


In [177]:
# simulating the binomial lattice model

# enter p, u, d
# generate a U
# set

# BLM gives us an estimation / simulation of stock prices after T time periods

def blm(S0, T, p_star, u, d):
    blmpath = [0 for k in range(T+1)]
    blmpath[0] = S0
    Ysamples = [Yrv(p,u,d) for k in range(T)]
    S = S0
    for k in range(1,T+1):
        S *= Ysamples[k-1]
        blmpath[k] = S
        print('Asset price at T =', k, 'is', blmpath[k])
    return blmpath

            
blm(S0, T, p_star, u, d)    

Asset price at T = 1 is 57.49999999999999
Asset price at T = 2 is 58.074999999999996
Asset price at T = 3 is 66.78625
Asset price at T = 4 is 67.4541125
Asset price at T = 5 is 68.128653625
Asset price at T = 6 is 78.34795166874999
Asset price at T = 7 is 90.10014441906247
Asset price at T = 8 is 103.61516608192184
Asset price at T = 9 is 104.65131774274106
Asset price at T = 10 is 120.34901540415221


[50,
 57.49999999999999,
 58.074999999999996,
 66.78625,
 67.4541125,
 68.128653625,
 78.34795166874999,
 90.10014441906247,
 103.61516608192184,
 104.65131774274106,
 120.34901540415221]

# Recycle Bin

__Problem 2:__ Recall the formula for computing the price $C_0$ of an option (derivative of the BLM stock prices) That yields a payoff at time $T$, denote by $C_T$:
$$ C_0 = \frac{1}{(1+r)^T}E^*(C_T), $$  

where $*$ refers to the fact that we must use the value $p^*$ instead of the original (real) $P$ for the up/down probability of the BLM. (The real value of $P$ is not needed for priciing.) Also recall that for $C_T = (S_T - K)^+$, the European call option, the expected value, $E^*(S_T-K)^+$ can be computed explicitly yielding the famous Black-Scholes-Merton option pricing formula:  
$$ C_0 = \frac{1}{(1+r)^T}\sum_{k=0}^{T} \left( \begin{array}{c}
T \\ k  \end{array} \right )(p^*)^k(1-p^*)^{T-k}(u^k d^{T-k}S_0-K)^+ . $$  

You are to use this formula to exactly obtain the price on the one hand, and then use Monte Carlo simulation on the other hand to compare and thus see how accurate the Monte Carlo method can be. 

Here are the parameters to use: $T = 10, r = 0.05, u = 1.15, d= 1.01, S_0 = 50, K = 70$. Recall that 
$$ p^* = \frac{1+r-d}{u-d} . $$  

For the Monte Carlo, use $n=100, n=1000, n=10,000$ _iid_ copies of $C_T$ (for averaging) to see how it gets more accurate as $n$ increases.

In [86]:
print('Using black scholes model, price C0 of a call contact is', round(St,2))

Using black scholes model, price C0 of a call contact is 2.11


In [96]:
def Yrv(p_star,u,d):
    U = random.random()
    if U <= p_star:
        return u
    return d
    

#def T_k(T, k):
   # poss_combos = math.comb(T,k)
    #return poss_combos

def left_side(p_star, k, T):
    ls = (p_star)**k * (1 - p_star)**(T-k)
    return ls

def right_side(u,k,d,T,S0,K):
    rs = (u**k*d**(T-k)*S0 - K)
    if rs > 0:
        return rs
    else:
        return 0

def black_scholes(T, k, r, u, d, S0, K, p):
    disc_rate = 1 / (1+r)**T
    C_zero = disc_rate*k*math.comb(T,k)*left_side(p_star, k, T)*right_side(u,k,d,T,S0,K)
    return C_zero


def bs_series(T, k, r, u, d, S0, K, p):
    bsresults = []
    for i in range(T):
        bsresults.append(black_scholes(T, i, r, u, d, S0, K, p))
        print('Potential payoff C at T =', i, 'is', bsresults[i])
    return bsresults

bs_series(T, k, r, u, d, S0, K, p)


Potential payoff C at T = 0 is 0.0
Potential payoff C at T = 1 is 0.0
Potential payoff C at T = 2 is 0.49019213614111024
Potential payoff C at T = 3 is 5.637778702318261
Potential payoff C at T = 4 is 10.419741157168945
Potential payoff C at T = 5 is 9.77550005484951
Potential payoff C at T = 6 is 5.515033156446881
Potential payoff C at T = 7 is 1.957951575628911
Potential payoff C at T = 8 is 0.4307607188766175
Potential payoff C at T = 9 is 0.053905642079866506


[0.0,
 0.0,
 0.49019213614111024,
 5.637778702318261,
 10.419741157168945,
 9.77550005484951,
 5.515033156446881,
 1.957951575628911,
 0.4307607188766175,
 0.053905642079866506]

# MC simulation below

In [44]:
n = 10

def blmpath_recursive(S0, n, p_star, u, d):
    blmpath = [0 for k in range(n+1)]
    blmpath[0] = S0
    for k in range(1,n+1):
        blmpath[k] = blmpath[k-1]*Yrv(p,u,d)
    return blmpath

blmpath_recursive(S0, n, p_star, u, d)

[50,
 50.5,
 58.074999999999996,
 58.65575,
 59.242307499999995,
 59.834730574999995,
 60.43307788075,
 69.49803956286249,
 79.92274549729186,
 80.72197295226478,
 81.52919268178742]

In [ ]:
T = 10
k = 1

def combos(T, k):
    return math.comb(T, k)

combos(T, k)

# p(k) = P(X=k) = (T, choose k)

In [ ]:
# use monte carlo simulation to to compare to the black scholes formula output 
# and see how accurate the monte carlo method can be

# n = 100
# n = 1000
# n = 10000





In [ ]:
disc_rate = 1 / (1+r)**T

p_star_k = p_star**k

hello = (1-p_star)**(T-k)

goodbye = (u**k)*(d**(T-k))*S0 - K


# building C0
# this block of code was working and now it no longer does? Why? I've made no changes? 

c0 = disc_rate*n_choose_k*p_star_k*hello*goodbye

abs(round(c0, 7))

In [ ]:
# yet the object c0 is still accurate?
c0

In [ ]:
abs(round(c0, 4))

__Problem 3__: With the same parameters as in Problem 2, price the _Asian call option:_ The payoff $C_T$ at atime $T$ is based on the average value of the stock over the $T$ time units:
$$ C_T = \left( \frac{1}{T} \sum_{i=1}^{T} S_i-K \right)^+ $$  

Use $n=100, n=1000, n=10,000$ _iid_ copies of $C_T$ (for averaging).

In [ ]:
daily_price = []
# use n=100, 1000, 10,000 copies of Ct for averaging..

# Payoff Ct is based on the average value of the stock over T time units
    # a loop which calculates the value of the stock Ct for each T time unit... 
    # an index which stores the value Ct for each time unit T
    # a formula to compute the average price of the stock over T time units

def asian_model(T):
    for i in range(T):
        Ct = abs(round((1/(i+1)*bern(p)- K),3))
        daily_price.append(Ct)
        i += 1
    
    Ct_avg = round(np.average(daily_price),3)

    return(Ct_avg)

asian_model(T)

In [ ]:
n = 1000

asian_model(T)

In [ ]:
n = 10000

asian_model(T)

__Problem 4__: With the same parameters as in Problem 2, but the additional parameters $n_1 = 4, n_2 =6,$ and $b=66$: price a _down and out barrier option_, that has payoff at time $T$ of  

$$ C_T = (S_T -K)^+ I \{ S_{n_1} \geq b, S_{n_2} \geq b \}.$$ 

Use $n=100, n=1000, n=10,000$ _iid_ copies of $C_T$ (for averaging).

In the above, recall that for any event $A$, $I\{A\}$ denotes the _indicator_ random variable defined by  
$$ I\{A\} = \left\{ \begin{array}{ll} 1 & \mbox{if $A$ occurs,} \\ 0 & \mbox{if $A$ does not occur.} \end{array} \right. $$

  
Here, $A = \{S_{n_1} \geq b, S_{n_2} \geq b\}$.


In [ ]:
n1 = daily_price[4]
n2 = daily_price[6]
b= 66

n = 100

Ct = abs(round((1/(i+1)*bern(p)- K),3))

# downandout = Ct+
    
Ct, n1, n2